window-height = "618.0"
window-width = "1000.0"
window-margin = "19.0"

button-radius = '50.0'

main-pane-button-active-0 = "A"
main-pane-button-active-1 = "A"
main-pane-button-active-2 = "D"
main-pane-button-active-3 = "D"
main-pane-button-active-4 = "D"
main-pane-button-active-5 = "D"
main-pane-button-active-6 = "D"
main-pane-button-active-7 = "D"
main-pane-button-active-8 = "D"
main-pane-button-active-9 = "D"
main-pane-button-active-10 = "D"
main-pane-button-active-11 = "D"

main-pane-button-text-0 = "MDM"
main-pane-button-text-1 = "準備"
main-pane-button-text-2 = ""
main-pane-button-text-3 = ""
main-pane-button-text-4 = ""
main-pane-button-text-5 = ""
main-pane-button-text-6 = ""
main-pane-button-text-7 = ""
main-pane-button-text-8 = ""
main-pane-button-text-9 = ""
main-pane-button-text-10 = ""
main-pane-button-text-11 = ""

center-label-info-0 = "マスタデータ管理ツール"
center-label-info-1 = "準備中"
center-label-info-2 = "準備中"
center-label-info-3 = "準備中"
center-label-info-4 = "準備中"
center-label-info-5 = "準備中"
center-label-info-6 = "準備中"
center-label-info-7 = "準備中"
center-label-info-8 = "準備中"
center-label-info-9 = "準備中"
center-label-info-10 = "準備中"
center-label-info-11 = "準備中"

